{"uuid": "6dbdbad8-bdd3-425a-8270-3ffdb103a0f0", "children": ["6c9c0ed6-36aa-40a0-9ec8-d7bc3d9cc4de"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: Browsing context has been discarded\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5\nNoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:630:5\nassert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:485:13\nassert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4\nGeckoDriver.prototype.maximizeWindow@chrome://remote/content/marionette/driver.sys.mjs:2619:15\ndespatch@chrome://remote/content/marionette/server.sys.mjs:318:40\nexecute@chrome://remote/content/marionette/server.sys.mjs:289:16\nonPacket/<@chrome://remote/content/marionette/server.sys.mjs:262:20\nonPacket@chrome://remote/content/marionette/server.sys.mjs:263:9\n_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:494:20\n\n", "trace": "  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\New folder\\python_selenium\\tests\\conftest.py\", line 64, in setup\n    driver.maximize_window()\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 990, in maximize_window\n    self.execute(command, params)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698906599528, "stop": 1698906612039}], "start": 1698906599528, "stop": 1698906612083}