{"uuid": "4939c89a-6b3e-40f2-9721-c0f831f67c86", "children": ["f97e704c-6392-4154-9a61-847218617c97"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=119.0.6045.160)\nStacktrace:\n\tGetHandleVerifier [0x005E72A3+45731]\n\t(No symbol) [0x00572D51]\n\t(No symbol) [0x0046880D]\n\t(No symbol) [0x0044F75E]\n\t(No symbol) [0x004BC11B]\n\t(No symbol) [0x004CB2D3]\n\t(No symbol) [0x004B7DD6]\n\t(No symbol) [0x004931F6]\n\t(No symbol) [0x0049439D]\n\tGetHandleVerifier [0x008F0716+3229462]\n\tGetHandleVerifier [0x009384C8+3523784]\n\tGetHandleVerifier [0x0093214C+3498316]\n\tGetHandleVerifier [0x00671680+611968]\n\t(No symbol) [0x0057CCCC]\n\t(No symbol) [0x00578DF8]\n\t(No symbol) [0x00578F1D]\n\t(No symbol) [0x0056B2C7]\n\tBaseThreadInitThunk [0x75CE7BA9+25]\n\tRtlInitializeExceptionChain [0x775DBD2B+107]\n\tRtlClearBits [0x775DBCAF+191]\n\n", "trace": "  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\New folder\\python_selenium\\tests\\conftest.py\", line 64, in setup\n    driver.maximize_window()\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 990, in maximize_window\n    self.execute(command, params)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\New folder\\python_selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1700425283216, "stop": 1700425292532}], "start": 1700425283216, "stop": 1700425292765}